# Generated by Django 5.0.3 on 2024-03-20 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
